apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-image-updater-config
  namespace: argocd
data:
  config.yaml: |
    git:
      writeBack:
        credentials:
          secretName: github-secret-argocd
    repositories:
      - url: git@github.com:chandhuDev/bank-of-anthos-k8.git
        credentials:
          secretName: github-secret-argocd