---
namespace: dev
replicas:
  - name: balancereader
    count: 1
  - name: contacts
    count: 1
  - name: frontend
    count: 1
  - name: ledgerwriter
    count: 1
  - name: loadgenerator
    count: 1
  - name: transactionhistory
    count: 1
  - name: userservice
    count: 1
images:
  - name: chandhudev0/boa-accountsdb
  - name: chandhudev0/boa-balancereader
  - name: chandhudev0/boa-contacts
  - name: chandhudev0/boa-frontend
  - name: chandhudev0/boa-ledgerdb
  - name: chandhudev0/boa-ledgerwriter
  - name: chandhudev0/boa-loadgenerator
  - name: chandhudev0/boa-transactionhistroy
  - name: chandhudev0/boa-userservice

resources:
  - ../../base
namePrefix: dev-
