apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - accounts-db.yaml
  - balance-reader.yaml
  - config.yaml
  - contacts.yaml
  - frontend.yaml
  - ledger-db.yaml
  - ledger-writer.yaml
  - load-generator.yaml
  - transaction-history.yaml
  - user-service.yaml
  - namespace.yaml